### ISSUE TITLE
'Illegal instruction' error

### ISSUE THREAD

**Issue by wikijm** [smeso/MTPwn#1]
Hi @smeso, 

On SAMSUNG Galaxy S5 (SM-G900F 6.0.1 G900FXXS1CQAV), I get this error message:

```
Device 0 (VID=04e8 and PID=6860) is a Samsung Galaxy models (MTP).

Files list:
PhoneName/10001/FolderName1
PhoneName/10001/FolderName2
PhoneName/20001/FolderName1
PhoneName/20001/FolderName2
Illegal instruction
```

Apparently, no compilation or execution error (except 'Illegal instruction') on 

>Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux
  
What's your needs to analyse?

**Comment by smeso** [comment]
Hi @wikijm !
Please, change CFLAGS and LDFLAGS in the Makefile as follows and try again:
```
CFLAGS=-g
LDFLAGS=-lmtp
```
Thanks for reporting the issue :)

**Comment by wikijm** [comment]
Thanks for your quick answer 😃 

I get this new error: 

> Floating point exception

P.S: My phone's name contains a '!'. I don't know if this might generate an issue.

**Comment by smeso** [comment]
What version of libmtp are you using?

**Comment by wikijm** [comment]
The command `dpkg --status libmtp-dev | grep ^Version` gives me `Version: 1.1.13-1`

**Comment by smeso** [comment]
Hi, I'm sorry for the delay.
Unfortunately, I'm not able to reproduce this issue.
Are you familiar with gdb?

**Comment by wikijm** [comment]
Hi, don't worry for the delay 😄 

I'm not familiar with gdb, but try me.

**Comment by smeso** [comment]
OK.
After having compiled mtpwn using the flags listed in https://github.com/smeso/MTPwn/issues/1#issuecomment-355042443
create a file with the following contents:
```
run
list
x/3i $rip-3
print $rip
x/4i $rip-4
print $rip
x/5i $rip-5
````
then run: `gdb --batch --command=THEFILEYOUJUSTCREATED ./mtpwn` and paste its output.
Thank you.

**Comment by wikijm** [comment]
Hi @smeso,
I'll make a try this week and give you a feedback soon :smile:

**Comment by SurajShahJaru** [comment]
root@localhost:~/Hack# ./ngrok http 80
Illegal instruction
root@localhost:~/Hack#
I have also same problem

**Comment by HAMM-WISS** [comment]
Me too:(
