### ISSUE TITLE
libusb error

### ISSUE THREAD

**Issue by helloitu** [smeso/MTPwn#2]
Full log of error.

Device 0 (VID=04e8 and PID=6860) is a Samsung Galaxy models (MTP).
ignoring libusb_claim_interface() = -6PTP_ERROR_IO: failed to open session, trying again after resetting USB interface
LIBMTP libusb: Attempt to reset device
ignoring libusb_claim_interface() = -6LIBMTP PANIC: failed to open session on second attempt
./mtpwn: There has been an error connecting

**Comment by smeso** [comment]
Does the `mtp-detect` command print similar errors?
